source 'https://rubygems.org'

gem 'sinatra'
gem 'activerecord'
gem 'bcrypt'
gem 'redcarpet'
gem 'json'
gem 'rails', '4.2.5'
gem 'uglifier', '>= 1.3.0'
gem 'jquery-rails'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0', group: :doc

group :production do 
	gem 'pg'
end

group :development, :test do
   gem 'byebug'
end

group :development do
  gem 'web-console', '~> 2.0'
  gem 'spring'
  gem 'sqlite3' 
  gem 'pry'
end

