require_relative 'album'
require_relative 'song'

mason_jar_twenties_album = Album.new()

mason_jar_twenties_album.add_song(Song.new(1, "Al Jolson", "Swanee", 1920))
mason_jar_twenties_album.add_song(Song.new(2, "Paul Whiteman", "Whispering", 1920))
mason_jar_twenties_album.add_song(Song.new(3, "George Gershwin", "Rhapsody in Blue", 1924))
mason_jar_twenties_album.add_song(Song.new(4, "Gene Austin", "Bye Bye, Blackbird", 1926))
mason_jar_twenties_album.add_song(Song.new(5, "Bessie Smith", "Downhearted Blues", 1923))
mason_jar_twenties_album.add_song(Song.new(6, "Ben Bernie", "Sweet Georgia Grown", 1925))
mason_jar_twenties_album.add_song(Song.new(7, "Vernon Dalhart", "The Prisoner's Song", 1925))
mason_jar_twenties_album.add_song(Song.new(8, "Eddie Cantor", "Makin' Whoopee", 1929))
mason_jar_twenties_album.add_song(Song.new(9, "Jimmie Rodgers", "T for Texas",1928))
mason_jar_twenties_album.add_song(Song.new(10, "Hoagy Carmichael","Stardust",1927))
mason_jar_twenties_album.add_song(Song.new(11, "Isham Jones","It Had to be You",1924))
mason_jar_twenties_album.add_song(Song.new(12, "Al Jolson","California, Here I Come",1924))
mason_jar_twenties_album.add_song(Song.new(13, "Fanny Brice","My Man",1922))
mason_jar_twenties_album.add_song(Song.new(14, "Gene Austin","My Blue Heaven",1927))
mason_jar_twenties_album.add_song(Song.new(15, "Fats Waller","Ain't Misbehavin",1929))
mason_jar_twenties_album.add_song(Song.new(16, "Frankie Trumbauer","Singin' the Blues",1927))
mason_jar_twenties_album.add_song(Song.new(17, "Bessie Smith","St Louis Blues",1925))
mason_jar_twenties_album.add_song(Song.new(18, "Paul Whiteman","Three O'Clock in the Morning",1922))
mason_jar_twenties_album.add_song(Song.new(19, "Al Jolson","April Showers",1922))
mason_jar_twenties_album.add_song(Song.new(20, "Ethel Waters","Am I Blue?",1929))
mason_jar_twenties_album.add_song(Song.new(21, "Helen Kane","I Wanna Be Loved By You",1928))
mason_jar_twenties_album.add_song(Song.new(22, "Arthur Gibbs & his gang","Charleston",1924))
mason_jar_twenties_album.add_song(Song.new(23, "Al Jolson","Toot Toot Tootsie",1922))
mason_jar_twenties_album.add_song(Song.new(24, "Duke Ellington","Black & Tan Fantasy",1928))
mason_jar_twenties_album.add_song(Song.new(25, "Paul Robeson","Ol' Man River",1928))
mason_jar_twenties_album.add_song(Song.new(26, "Al Jolson","Sonny Boy",1928))
mason_jar_twenties_album.add_song(Song.new(27, "Isham Jones","Swingin' Down the Lane",1923))
mason_jar_twenties_album.add_song(Song.new(28, "Jack Smith","Me & My Shadow",1927))
mason_jar_twenties_album.add_song(Song.new(29, "Louis Armstrong","West End Blues",1928))
mason_jar_twenties_album.add_song(Song.new(30, "Billy Jones","Yes! We Have No Bananas",1923))
