# A sample Gemfile
source "https://rubygems.org"

# gem "rails"
gem "sinatra"
gem "activerecord"
gem "bcrypt"
group :development do
  gem "sqlite3"
  gem "pry"
end
group :production do
  gem "pg"
end
